version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Briscoooe/Discogrify/go/main
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: ls
      - run: go build
      - run: go test

